#!/usr/bin/env bash
# This script transfers a file from our client to a server
# Accepts 4 parameters


if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

FILE=$1
IP=$2
USER=$3
SSH=$4
DIR="~/"

scp -B -o StrictHostKeyChecking=off -i "${SSH}" "${FILE}" "${USER}@${IP}:${DIR}"
