#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine

# update local package index
apt-get update

# install Nginx
apt-get -y install nginx

# Adjust firewall
ufw allow 'Nginx HTTP'

# default text
echo 'Hello World!' > /var/www/html/index.html

# Define replacement string with proper line continuation and escaping
r_string="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/github.com\/functionguyy;\n\t}\n"

# Modify location block in place
sed -i "s/^ *server_name _;/$r_string/" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

