#!/usr/bin/env bash
# This script configures Ngnix on a new Ubuntu machine

# update local package index
apt-get update

# install Ngnix
apt-get -y install nginx

# Adjust firewall
ufw allow 'Nginx HTTP'

# default text
echo 'Hello World!' > /var/www/html/index.html

# modify location block in place
sed -i 's/^ *location \//c\    
    location \/redirect_me {\
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 \
    }' /etc/nginx/sites-available/default

service nginx restart
