#!/usr/bin/env bash
# This script configures Ngnix on a new Ubuntu machine

# update local package index
apt-get update

# install Ngnix
apt-get -y install nginx

# Adjust firewall
ufw allow 'Nginx HTTP'

# default text
echo 'Hello World!' > /var/www/html/index.html

r_string="server_name _;\n\n\tlocation \/redirect_me {\n\treturn 301\
          https:\/\/github.com\/functionguyy;"
# modify location block in place
sed -i "s/^ *server_name _;/$r_string" /etc/nginx/sites-available/default

service nginx restart
