#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine

# update local package index
apt-get update

# install Nginx
apt-get -y install nginx

# Adjust firewall
ufw allow 'Nginx HTTP'

# default text
echo 'Hello World!' > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Define replacement string with proper line continuation and escaping
r_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301\
 https:\/\/github.com\/functionguyy;\n\t}"

# add location block in place
sed -i "s/server_name _;/$r_string/" /etc/nginx/sites-available/default

e_string="error_page 404 /404.html;"

#modify location / block to return custom 404 error page
sed -i "s/try_files \$uri \$uri\/ =404;/$e_string/"

# Restart Nginx
service nginx restart

