#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine

# update local package index
apt-get update

# install Nginx
apt-get -y install nginx

# Adjust firewall
ufw allow 'Nginx HTTP'

# initialize variables
HOSTNAME=$(hostname)
NGINX_CONF="/etc/nginx/sites-available/default"


# default text
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Define replacement string with proper line continuation and escaping
r_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301\
 https:\/\/github.com\/functionguyy;\n\t}"

# add location block in place
sed -i "s/server_name _;/$r_string/" $NGINX_CONF

e_string="error_page 404 \/custom_404.html;"

# modify location / block to return custom 404 error page
sed -i "s/try_files \$uri \$uri\/ =404;/$e_string/" $NGINX_CONF

# add custom header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By '"$HOSTNAME"';' $NGINX_CONF


# Restart Nginx
service nginx restart

