#!/usr/bin/env bash
# This script installs and configures HAproxy on your server

# update local package index
apt-get update

# install HAproxy
apt-get -y install haproxy


HAPROXY_CONFIG="/etc/haproxy/haproxy.cfg"
HAPROXY_INIT="/etc/default/haproxy"

init_config="ENABLED=1"

echo "$init_config" >> $HAPROXY_INIT

server_config=\
"
frontend myfrontend
        mode http
	bind :80
        default_backend mybackend

backend mybackend
        balance roundrobin
        server 167954-web-01 54.166.61.137:80 check
        server 167954-web-02 54.157.184.234:80 check
"
echo "$server_config" >> $HAPROXY_CONFIG
service haproxy restart
