#!/usr/bin/env bash
# This script installs and configures HAproxy on your server

# update local package index
apt-get update

# install HAproxy
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*



HAPROXY_CONFIG="/etc/haproxy/haproxy.cfg"

server_config=\
"
frontend myfrontend
        mode http
	bind *:80
        default_backend mybackend
backend mybackend
        balance roundrobin
        server 167954-web-01 54.166.61.137:80 check
        server 167954-web-02 54.157.184.234:80 check
"
echo "$server_config" >> $HAPROXY_CONFIG
service haproxy restart
