#!/usr/bin/env bash
# This script installs and configures HAproxy on your server

# update local package index
apt-get update

# install HAproxy
apt-get install haproxy

HAPROXY_CONFIG="/etc/haproxy/haproxy.cfg"
HAPROXY_INIT="/etc/default/haproxy"

init_config="ENABLED=1"

echo "$init_config" >> $HAPROXY_INIT

server_config=\
"
frontend myfrontend
        mode http
	bind :80
        default_backend mybackend

backend mybackend
        balance roundrobin
        server web-01 web-01.gilbertadikankwu.tech:80 check
        server web-02 web-02.gilbertadikankwu.tech:80 check
"
echo "$server_config" >> $HAPROXY_CONFIG
service haproxy restart
