#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# It displays the username, user id, Home directory path for the user
FILENAME="/etc/passwd"

if [ ! -r "$FILENAME" ]
then
	echo "Error: Can not read $FILENAME"
	exit 1
fi

while read -r FILELINE
do
	echo "$FILELINE" | cut -d ":" -f 1,3,6 
done < "$FILENAME"
