#!/usr/bin/env bash
# This script displays the vistor IP along with the HTTP from the Apache log
# file

LOG_FILE="apache-access.log"

awk '{if ($8 ~ /\"/) print $1,$9; else print $1,$7}' < $LOG_FILE
