#!/usr/bin/env bash
# This script displays the vistor IP along with the HTTP from the Apache log
# file

LOG_FILE="apache-access.log"

awk '{print $1,$9}' < $LOG_FILE | sort -k 1 | uniq -c | sort -nr
