#!/usr/bin/env bash
# This script loops from 1 to 10 and displays "bad luck" for the 4th loop
# iteration, "good luck" for the 8th loop iteration, "Best School" for the
# other iterations
LIMIT=10
mystring="Best School"
badstring="bad luck"
goodstring="good luck"
n=1

while (( n <= LIMIT ))
do
	if [ "$n" -eq 4 ]
	then
		echo "$badstring"
	elif [ "$n" -eq 8 ]
	then
		echo "$goodstring"
	else
		echo "$mystring"
	fi
	(( n++ ))
done
