#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed
FILE_LIST=$(ls)

for line in $FILE_LIST
do
	# process with cut using field option and print the second field 
	echo "$line" | cut -d "-" -f 2-
done
