#!/usr/bin/env bash
# This script gives information about a file
FILENAME="school"

# test if the file exist
if [ -e "$FILENAME" ]
then
	echo "school file exists"

	# test if file is empty -s returns True for file with size > 0
	if [ -s "$FILENAME" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# test if file is a regular
	if [ -f "$FILENAME" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
