#!/usr/bin/env bash
# This script installs ufw firewall on your ubuntu server

# update local package index
apt-get update

# install UFW
apt-get -y install ufw


ufw default deny incoming

ufw default allow outgoing


ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw enable
